### ISSUE TITLE
Some 3rd level nav items aren't highlighted

### ISSUE THREAD

**Issue by r0mant** [gravitational/next#123]
Examples:

https://goteleport.com/teleport/docs/database-access/guides/postgres-aws/
https://goteleport.com/teleport/docs/database-access/guides/mysql-aws/

If you select either of these, the Database Access section will be collapsed and the respective link won't be highlighted as active. Other links under the same subsection work fine.

**Comment by iAdramelk** [comment]
@r0mant its trailing slashes: https://github.com/gravitational/teleport/blob/branch/v6/docs/config.json#L47-L48

Docs engine automatically redirects you to the URL with the `/` at the end and then tries to find current item in the menu by matching current URL to the ones in config. And because it didn't match it didn't select anything. I can add logic that checks config URLs to for trailing `/`, but fixing them in config will probably be easier.

**Comment by r0mant** [comment]
@iAdramelk Ah yes, somehow I missed the trailing slashes there. Yeah, fixing them in the config is definitely easier, I'll try that later today and close the ticket. Thanks!
