### ISSUE TITLE
Code snippet

### ISSUE THREAD

**Issue by klizhentas** [gravitational/next#166]
## Description

Code snippet should add `$` to all code automatically. Remove all `$` from all code snippets.

**Comment by inertial-frame** [comment]
As a follow-up to this - is it possible to both add the `$`  symbol before code snippets but maybe wrap it in a separate element from the block that gets copied on selection?

Personally, I prefer having `$` depicted/rendered (stresses non-root access, helps clarify lines/commands) but not having one copied (since it's not always appropriate for the terminal used, user type, etc.).

I think @benarent requested this feature too: https://github.com/gravitational/next/issues/96

**Comment by sshahcodes** [comment]
Adding `$` automatically will not be an easy task since it's very hard to predict when and where to add it. For example in a multi-line code block like below, how can we decide that `$` should be placed before specific line? 
```
# Create local config and data directories for teleport, which will be mounted into the container
mkdir -p ~/teleport/config ~/teleport/data

# Generate a sample teleport config and write it to the local config directory.
# This container will write the config and immediately exit - this is expected.
docker run --hostname localhost --rm \
  --entrypoint=/bin/sh \
  -v ~/teleport/config:/etc/teleport \
  quay.io/gravitational/teleport:6 -c "teleport configure > /etc/teleport/teleport.yaml"

```

As mentioned in #96 which references Heroku sample, I looked into Docker docs website and it does the same. i.e. makes `$` unselectable using `user-select: none`. If you look at the [docker docs source file](https://raw.githubusercontent.com/docker/docker.github.io/master/engine/install/ubuntu.md) , they do have `$` in `.md` files. So they must be using some transformer to make it unselectable while showing in the page. They do not offer copy to clipboard feature though!. Neither does Heroku. 


Currently, in our case, code selection can be done in two ways:
1. Directly selecting text using keyboard/mouse text select: `user-select: none` works for this case but we will need a transformer to inject CSS for `$` character.  
2. Using copy to clipboard button (rendered inside code block): making `$` character unselectable using `user-select: none` will not work here because it is copied from `codeRef.current.innerText` of HTMLDivElement (css feature will not have effect on HTML inner dom)

So we have two possible solutions:
1. [ ] Build a `.md` transformer plugin that will render `$` as `user-select: none` element. This will solve the first case described above.
2. [ ] Manually filter out `$` character from copied content when using the Copy button. This will solve the second case described above.

In any case, `$` should be placed inside the `.md` file. Aso, it makes it easier to read code blocks this way if reading directly from `.md` file.

-------------------

**Note:** If we only use one command per code block (without comments), we can also use CSS style as :
```
& ::before {
   content: "$ ";
}
``` 
and this will work in both the cases.
