### ISSUE TITLE
Blog Repository

### ISSUE THREAD

**Issue by alexwolfe** [gravitational/next#807]
You will be tasked with moving the blog to a separate repository
- Create a separate repository for the blog
- Transfer all remaining blog posts to the repository
- Remove any unused components in this repository
- Add [Contentful](https://www.contentful.com/) as a headless CMS option
- Be prepared to present you repository. The goal will to make it simple and easy for anyone on the development team to understand how this repository is setup, how it interacts with the headless cms, and how to add/update/remove content. 

Some videos on how to use contentful can be found here: https://www.youtube.com/watch?v=m9mNsYJbkNg&list=PL4cUxeGkcC9jClk8wl1yJcN3Zlrr8YSA1

**Comment by C-STYR** [comment]
@Alqanar I have created the repository for you: `gravitational/blog` and given you admin access.  Further notes: 
- this repo should mirror the current state of `/next` but won't be linked to it as a submodule.  
- further to the point above, the relevant dependencies and configurations should be copied
- the relevant components should be copied (for now - we may institute a shared component library later)
- no unused components need to be copied
- no storybook or storybook entries need to be copied
- `package.json` scripts should be simplified accordingly

**Comment by Alqanar** [comment]
1. `the relevant components should be copied (for now - we may institute a shared component library later)`
In my opinion, if you have plans to implement it, you should do it right away, since the site and blog have a lot of common components. If we start the migration by copying components, there probably won’t be enough time later to redo it using components from another repository.
If components are being duplicated, it possible to loose changes in mirror-component when you change it in one repository. In other words it would be complicated to keep components in sync. So, common-ish components will be visually and logically inconsistent.

2. `Add Contentful as a headless CMS option`
The Contentful product requires content, images, etc. storing in it’s own database. If we move to it, we will need to migrate around 300 MDX articles already to Contentful.
Using both the mdx article format and the Contentful database at the same time is not practical. This is because there would be a lot of code (850 lines of code in total) which would only be used by those 300 legacy articles, and the code couldn’t be removed until there is at least one article in the blog of those 300 articles.
Also we will need to come up with integration for articles derived from Contentful and in mdx format (i.e. if it’s legacy article do that otherwise do this).

**Comment by alexwolfe** [comment]
1. This is understood and expected. Initially copying the components over is fine and in the future we can create a shared repo and use a git submodule if desired. We don’t need to do so now.

2. Yes its true contentful houses much of this content until build time. I believe you can investigate the approach of having new articles on contentful and not transferring the existing articles that have already been migrated. Over time we can decide on Migrating the existing articles. However, when you split if off to a new repo, Contentful should be a PR on that repo not merged into main. This will allow us to experiment as we still publish blogs each week.

**Comment by Alqanar** [comment]
**Stage I. Transferring a blog with existing articles in mdx-format and related logic.**

1. Transferring infrastructure parts (configs). Optimise this part only for the blog.  

2. If it is already decided that we now do not create a common repository with components, then copying and transferring to a new repository components used by the blog, including header, footer, etc. common elements with the site 

  **Pros**:    
    a) less time consumption;
     b) the work of the articles and the main page of the blog without much change; 
     
     **Cons**: 
       a) possible logical and visual mismatch in the components, when you make changes to a component in only one repository;           b) making changes to the same component several times in different repositories - additional time consumption, additional responsibility of developers - not to forget that this component is duplicated in another repository;   
       c) if the components will be transferred to a common repository later, it may cause more time because of the larger code base;   
     
     3. Moving templates, plugins, and helpers to make the blog work correctly;
    
      4. Moving articles that are already migrated to mdx now;
      
        5. Complete the necessary steps to be able to work next from a subfolder. This means to fix all the urls in the blog so that they do not have /blog/ and fix all the links in the header and footer so that they have the full address of goteleport.com
 
 6. Create a separate source map and import it into gravitational/next;
 
 7. Include proxy in gravitational/next;  
 
 8. There is also a question of how we will work forms, specifically the subscription form. So, will we need to copy the backend for the forms as well or try to use it from gravitational/next;  
 
 **Q**: Right now, the articles that came out before January 6 are migrated to mdx format. Do I need to migrate all the articles that came out between then and the release of this repository with the articles? Or will you do it yourself?
 
   **The summary of the first stage**: There is nothing particularly complicated about these tasks, but there are several tasks that need to be researched. So I think I will accomplish this step in a **1,5 weeks**. Not counting the migration of new articles that came out after January 6. If I migrate new articles, they will take another 3-4 days.   
   
   
   **Stage II. Connection of headless CMS**   
   
   Initially I would like to say that headless CMS c Next.js quite a lot. The choice in favour of Contentful already defined? You can consider different options.  There are several open source CMSs, such as Strapi. Very lively repository, at first glance has the same features as Contentful. Free, but there are certain paid features (but $9 a month doesn't seem like a lot of money at all). Liked the ability to publish articles from Strapi to Multiple Platforms (dev.to, Medium, Hashnode), which can bring additional traffic to the site and increase visibility in the community.
    A controversial point with Strapi is that the base with the articles must be stored on your servers. That is, you may need to support that database. But there will be no disadvantages with the fact that the project may close and the entire database with articles may be lost if the database with articles is on a third-party service. 
    
      Connecting CMS and leaving articles in mdx-format is quite difficult to perform and will certainly require more time than stopping only on CMS or on mdx. It does not really matter which headless CMS you choose (the main thing is that there were integrations with Next.js).  
      
      Below I consider the pros and cons of CMS (any CMS, without specifying), mdx and sharing.   
      
       **Pros of CMS**:    
         a) Easier article publication (including its writing);
         b) Removal of quite a large amount of code with helper, template and code that describes the logic for blog articles (if you give up completely from mdx-format); 
         c) Acceleration of build, no memory problems (serverless functions). 

    **Cons of CMS**:  
      a) The time required to study the CMS, its features and limitations; 
      b) The time required to change the logic of working with data that comes from CMS;
      c) Probably will not work interactive components such as a subscription block in the middle of the article (in Contenful will work, but it takes a lot of preparation. Strapi not studied this issue); 
      d) Transfer of existing articles from mdx-format to CMS (if you give up completely from mdx-format);  
      e) Can' t show posts from CMS without full rebuild, which will have to be run manually. Perhaps there are some automatic options, but this needs to be researched;
  f) The logic of sitemap and rss generation is tricky.
  
  Since I am not familiar with the CMS, so it is quite difficult to estimate the time. But I think that tentatively connect the CMS will take 2 weeks, but I'll lay another week for unforeseen bugs, learning, etc., that is **3 weeks**.  
  
  About the disadvantages of sharing and CMS and mdx-format, I wrote, but I'll repeat, so it would be in one place: 
    
    **Pros of sharing CMS and mdx-format**:  
    a) No need to transfer articles already migrated to mdx-format in CMS; 
    b) Further possibility of using mdx-format, if someone prefers this format;  
    
    **Cons of sharing CMS and mdx-format**.
      In fact, the joint use of CMS and mdx-format will collect all the disadvantages of both formats and add a little more.   
        a) The time required to study the CMS, its capabilities and its limitations; 
        b) The time required to change the logic of working with data that comes from CMS;   
        c) Perhaps will not work mdx components such as subscriptions in the middle of post (in Contenful will work, but for this requires a lot of preparation. On Strapi did not study this issue);   
        d) Can' t show posts from CMS without full rebuild, which will have to be run manually. Perhaps there are some automatic options, but this needs to be researched;   
        e) The logic of sitemap and rss generation is tricky;   
        f) No advantage with the acceleration of the build;   
        g) The time required to find and implement a solution with the joint use of different data formats (from mdx and from CMS).   
        h) There may also be problems with filtering by tags from different sources. 
        
        Considering all of the above, to combine articles in mdx-format and from CMS is possible, but in the end the work of this designer may be unstable, also will require additional time for research and implementation. Specific time for implementation here is even more difficult to call than just with CMS, but I think I should be able to do it in **1,5 weeks**.  
        
        **Total**:  
        - the implementation of the transfer of the blog with the existing articles in mdx-format and related logistics (first phase), I need roughly a 1,5 weeks + 3-4 days, if I need to transfer additional articles that were published after January 6.  
        
        - to implement the connection of headless CMS (second stage) I will need tentatively 3 weeks + tentatively 1.5 weeks, if I need to find and implement a solution for the joint use of CMS and mdx-format.

**Comment by alexwolfe** [comment]
Thanks for the proposal. Moving forward I would like to not focus on pros/cons with these proposals. Instead the format should be as follows to provide maximum information in a less opinionated format. 

1. Clearly defined list of tasks required to complete the project
2. Components that have multiple solutions (ex. CMS) and what the options are
3. *If there are multiple solutions, the major feature differences (ex. CMS) 
4. A time estimate for completion of each phase
5. Considerations 
6. Questions 

This will be more efficient for us moving forward as the group is often not aware of all the other tasks and decisions we are making as a company. The pro/cons is an opinion and honestly not helpful as much of it is subjective, no exhaustive, and in many cases not actionable. 

Thanks again for your help with this. As the next course of action I'll split these into different tickets so we can define the scope in smaller sprints. 

1. Moving the blog repository
2. Choosing a CMS and implementing it 

Each of these will have a few steps involved which I'll outline in the new tickets.
